#!/usr/bin/env ruby

Dir.glob('source/diary/**/*.md.erb').each do |file|
  content = File.read(file)
  # next unless content.match?(/^title: 東品川ごはん/)

  if content =~ /\A---\n(.*?)\n---/m
    md = $1.match(/^tags: (.*)/i)
    # puts md
    if md
      tags = md[1].split(/,/)
      tags.filter { |t| t.strip! }
      new_tags = []
      tags.each do |tag|
        if tag.match?(/(\w\w*) food/i)
          new_tags.push(tag.sub(/ food/i, ''))
        elsif tag.match?(/^yokohama iekei$/i)
          new_tags.push('iekei')
        elsif tag.match?(/^cataract .*$/i)
          new_tags.push('cataract')
        elsif tag.match?(/^animals$/i)
          new_tags.push('animal')
        elsif tag.match?(/^documents$/i)
          new_tags.push('document')
        elsif tag.match?(/^walking$/i)
          new_tags.push('walk')
        elsif tag.match?(/^usa$/i)
          new_tags.push('us')
        elsif tag.match?(/^business[- ]trip$/i)
          new_tags.push('business')
        elsif tag.match?(/^disneyland$/i)
          new_tags.push('disney')
        elsif tag.match?(/^newyear$/i)
          new_tags.push('new year')
        elsif tag.match?(/^babies$/i)
          new_tags.push('baby')
        elsif tag.match?(/^siblings$/i)
          new_tags.push('sibling')
        elsif tag.match?(/^bicycle$/i)
          new_tags.push('bike')
        elsif tag.match?(/^cycling$/i)
          new_tags.push('bike')
        elsif tag.match?(/^bento$/i)
          new_tags.push('lunchbox')
        elsif tag.match?(/^camping$/i)
          new_tags.push('camp')
        elsif tag.match?(/^solo camp$/i)
          new_tags.push('solo')
        elsif tag.match?(/^dogs$/i)
          new_tags.push('dog')
        elsif tag.match?(/^insects$/i)
          new_tags.push('insect')
        elsif tag.match?(/^noodles$/i)
          new_tags.push('noodle')
        elsif tag.match?(/^undoukai$/i)
          new_tags.push('sports day')
        elsif tag.match?(/^soccer$/i)
          new_tags.push('football')
        elsif tag.match?(/^technical$/i)
          new_tags.push('tech')
        elsif tag.match?(/^technology$/i)
          new_tags.push('tech')
        elsif tag.match?(/^ren$/i)
          new_tags.push('son')
        elsif tag.match?(/^riri$/i)
          new_tags.push('daughter')
        elsif tag.match?(/^hotpot$/i)
          new_tags.push('hot pot')
        elsif tag.match?(/^friends$/i)
          new_tags.push('friend')
        elsif tag.match?(/^hiking$/i)
          new_tags.push('trail')
        elsif tag.match?(/^scifi$/i)
          new_tags.push('sci-fi')
        elsif tag.match?(/^morning activity$/i)
          new_tags.push('morning')
        elsif tag.match?(/^company event$/i)
          new_tags.push('event')
        elsif tag.match?(/^skiing$/i)
          new_tags.push('ski')
        elsif tag.match?(/^hot spring$/i)
          new_tags.push('onsen')
        elsif tag.match?(/^photos$/i)
          new_tags.push('photo')
        elsif tag.match?(/^photography$/i)
          new_tags.push('photo')
        elsif tag.match?(/^children$/i)
          new_tags.push('kids')
        elsif tag.match?(/^kindergarten$/i)
          new_tags.push('daycare')
        elsif tag.match?(/^nursery$/i)
          new_tags.push('daycare')
        elsif tag.match?(/^theme-?park$/i)
          new_tags.push('theme park')
        elsif tag.match?(/^sports-?day$/i)
          new_tags.push('sports day')
        elsif tag.match?(/^newborn$/i)
          new_tags.push('birth')
        elsif tag.match?(/^potato digging$/i)
          new_tags.push('potato')
        elsif tag.match?(/^wfh$/i)
          new_tags.push('telework')
        else
          new_tags.push(tag)
        end
      end
      
      # Add 'meguro' tag if title is '目黒ごはん' and 'meguro' is not already present
      if content.match?(/^title: 目黒ごはん/) && !new_tags.include?('meguro')
        new_tags.push('meguro')
      end

      if tags != new_tags
        puts "#{tags.join(', ')} -> #{new_tags.join(', ')}"
        update_content = content.sub(/^tags: .*$/, "tags: #{new_tags.join(', ')}")
        File.write(file, update_content)
      end
    end
  end
end
