all::
	op run --env-file="${HOME}/.env" -- python3 ./gen_image.py
year::
	op run --env-file="${HOME}/.env" -- python3 ./gen_image.py 2025

auth::
	op run --env-file="${HOME}/.env" -- python3 ./auth.py
